# doc: https://github.com/wei/pull#basic-setup
# manually trigger: https://pull.git.ci/process/${fork-user}/BookedScheduler
# pull from: https://github.com/effgarces/BookedScheduler
version: "1"
rules:
  - base: develop
    upstream:  effgarces:develop
    mergeMethod: rebase
  - base: master
    upstream: effgarces:master
    mergeMethod: hardreset
